version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  gestsup:
    build: .
    ports:
      - 3010:80
    environment:
      PHP_VERSION: 8.1
      GESTSUP_VERSION: 3.2.30
    depends_on:
      - mariadb
    volumes:
      - ./html:/var/www/html/
    networks:
      - internal
      - web
    labels:
      - traefik.http.routers.gestsup.rule=Host(`xxx.domain.fr`)
      - traefik.http.routers.gestsup.tls=true
      - traefik.http.routers.gestsup.tls.certresolver=myresolver
      - traefik.docker.network=web
    container_name: gestsup

  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxxx
      MYSQL_DATABASE: bsup
      MYSQL_USER: gestsup
      MYSQL_PASSWORD: yyyyyyyyy
    restart: on-failure
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - internal
    container_name: mariadb_gestsup

volumes:
  html: {}
  mysql: {}
